### ISSUE TITLE
建议对B3LYP，X-YZg等常见关键词也加上高亮

### ISSUE THREAD

**Issue by supernova4869** [mizu-bai/VSCode-Gaussian-Input-File-Support#1]
一些常用的方法和基组，例如B3LYP，M062X等
另外能否考虑参照sob老师博文，把泛函、基组的选择方法加进去呢，这样就不用每次打开网页了

**Comment by mizu-bai** [comment]
It's my fault. I also found `b3lyp` has no syntax highligh, so more methods and basises will be supported. For adding sob's advices, I am worried about that he does not allow others to reprint the articles.

**Comment by mizu-bai** [comment]
Now you can try recent new release!
