### ISSUE TITLE
[Bug Report]不能正确识别氘和氚

### ISSUE THREAD

**Issue by LaoshuBaby** [mizu-bai/VSCode-Gaussian-Input-File-Support#2]
如图，使用本插件在VSCode中打开gjf文件时，不能正确识别D和T为H的同位素，所以没有对他们进行着色。

（部分数据因涉及暂无法公开的实验数据，故打码）

![图片](https://user-images.githubusercontent.com/42690037/161032614-ff65c6c9-a909-4709-b7a3-f6f53d72bdb5.png)

可能涉及到的代码为：

https://github.com/mizu-bai/VSCode-Gaussian-Input-File-Support/blob/59f1666c559c5f1190f470316fbada0bcd7caa03/syntaxes/gjf.tmLanguage.json#L121-L124

**Comment by mizu-bai** [comment]
Thanks for this.
